site_name: MSYS2
site_description: Software Distribution and Building Platform for Windows
docs_dir: web/
theme:
    name: material
    logo: 'logo.svg'
    favicon: 'favicon.ico'
    palette:
        primary: 'indigo'
        accent: 'indigo'
    features:
        - instant
    custom_dir: overrides

extra_css:
    - 'stylesheets/extra.css'

extra:
    social:
        - icon: 'fontawesome/brands/github'
          link: 'https://github.com/msys2'
        - icon: 'fontawesome/brands/gitter'
          link: 'https://gitter.im/msys2/msys2'
        - icon: 'fontawesome/brands/twitter'
          link: 'https://twitter.com/msys2org'

site_url: https://www.msys2.org
repo_url: https://github.com/msys2/msys2.github.io
edit_uri: edit/source/web/

markdown_extensions:
    - meta
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
    - 'Getting Started': index.md
    - news.md
    - Package Index: https://packages.msys2.org
    - Documentation:
        # For users of MSYS2 which just use the provided software
        # or develop their software using MSYS2 provided packages/tools.
        - docs/what-is-msys2.md
        - docs/who-is-using-msys2.md
        - docs/environments.md
        - docs/ci.md
        - docs/terminals.md
        - docs/package-management.md
        - docs/filesystem-paths.md
    - Development:
        # For MSYS2 developers, maintaining, creating packages, porting packages,
        # infrastructure, mirrors etc and everything else.
        - dev/mirrors.md
        - dev/keyring.md
    - Other Topics:
        # Old stuff that should ideally move to the above categories in the future
        - wiki/Home.md
        - wiki/Contributing-to-MSYS2.md
        - wiki/Creating-Packages.md
        - wiki/Devtopics.md
        - wiki/Distributing.md
        - wiki/FAQ.md
        - wiki/GDB-qtcreator.md
        - wiki/History.md
        - wiki/How-does-MSYS2-differ-from-Cygwin.md
        - wiki/Launchers.md
        - wiki/MSYS2-installation.md
        - wiki/MSYS2-introduction.md
        - wiki/MSYS2-reinstallation.md
        - wiki/Packages.md
        - wiki/Porting.md
        - wiki/Setting-up-SSHd.md
        - wiki/Signing-packages.md
        - wiki/Sudo.md
        - wiki/Terminals.md
        - wiki/JIT-Debugging.md
    - 'contact.md'