site_name: MSYS2
site_description: Software Distribution and Building Platform for Windows
docs_dir: web/
theme:
    font: false
    name: material
    logo: 'logo.svg'
    favicon: 'favicon.ico'
    palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - scheme: default
        media: "(prefers-color-scheme: light)"
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        primary: 'indigo'
        accent: 'indigo'
      - scheme: slate
        media: "(prefers-color-scheme: dark)"
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
        primary: 'blue'
        accent: 'blue'

    features:
        - navigation.instant
        - content.action.edit
        - content.code.copy

    custom_dir: overrides

plugins:
  - search
  - privacy

extra_css:
    - 'stylesheets/extra.css'
    - 'stylesheets/fonts.css'

extra:
    alternate:
      - name: Deutsch (de)
        link: https://www-msys2-org.translate.goog/?_x_tr_sl=en&_x_tr_tl=de
        lang: de
      - name: Español (es)
        link: https://www-msys2-org.translate.goog/?_x_tr_sl=en&_x_tr_tl=es
        lang: es
      - name: Français (fr)
        link: https://www-msys2-org.translate.goog/?_x_tr_sl=en&_x_tr_tl=fr
        lang: fr
      - name: 日本语 (ja)
        link: https://www-msys2-org.translate.goog/?_x_tr_sl=en&_x_tr_tl=ja
        lang: ja
      - name: 한국어 (ko)
        link: https://www-msys2-org.translate.goog/?_x_tr_sl=en&_x_tr_tl=ko
        lang: ko
      - name: 中文 (zh)
        link: https://www-msys2-org.translate.goog/?_x_tr_sl=en&_x_tr_tl=zh
        lang: zh
    social:
        - icon: 'fontawesome/brands/github'
          link: 'https://github.com/msys2'
        - icon: 'fontawesome/brands/mastodon'
          link: 'https://fosstodon.org/@msys2org'
        - icon: 'fontawesome/brands/discord'
          link: 'https://discord.gg/jPQdRdDcT9'
        - icon: 'fontawesome/brands/bluesky'
          link: 'https://bsky.app/profile/msys2org.bsky.social'

site_url: https://www.msys2.org
repo_url: https://github.com/msys2/msys2.github.io
edit_uri: edit/main/web/

markdown_extensions:
    - meta
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
    - 'Getting Started': index.md
    - news.md
    - Package Index: https://packages.msys2.org
    - Documentation:
        # For users of MSYS2 which just use the provided software
        # or develop their software using MSYS2 provided packages/tools.
        - docs/what-is-msys2.md
        - docs/who-is-using-msys2.md
        - docs/environments.md
        - docs/updating.md
        - docs/ci.md
        - docs/terminals.md
        - docs/ides-editors.md
        - docs/installer.md
        - Package Management:
          - docs/package-management.md
          - docs/package-naming.md
          - docs/repos-mirrors.md
          - docs/package-management-tips.md
          - docs/package-management-faq.md
        - docs/filesystem-paths.md
        - docs/symlinks.md
        - docs/configuration.md
        - Languages & Tools:
          - docs/cmake.md
          - docs/autotools.md
          - docs/python.md
          - docs/git.md
          - docs/c.md
          - docs/cpp.md
          - docs/pkgconfig.md
          - docs/pacman.md
        - docs/windows_support.md
        - docs/faq.md
    - Development:
        # For MSYS2 developers, maintaining, creating packages, porting packages,
        # infrastructure, mirrors etc and everything else.
        - Packaging:
          - dev/new-package.md
          - dev/update-package.md
          - dev/package-guidelines.md
          - dev/package-licensing.md
          - dev/pkgbuild.md
        - dev/mirrors.md
        - dev/keyring.md
        - dev/python.md
        - dev/build-process.md
        - dev/vulnerabilities.md
        - dev/accounts.md
    - Other Topics:
        # Old stuff that should ideally move to the above categories in the future
        - wiki/Home.md
        - wiki/Creating-Packages.md
        - wiki/Devtopics.md
        - wiki/Distributing.md
        - wiki/GDB-qtcreator.md
        - wiki/History.md
        - wiki/How-does-MSYS2-differ-from-Cygwin.md
        - wiki/Launchers.md
        - wiki/MSYS2-installation.md
        - wiki/MSYS2-introduction.md
        - wiki/MSYS2-reinstallation.md
        - wiki/Porting.md
        - wiki/Setting-up-SSHd.md
        - wiki/Signing-packages.md
        - wiki/Sudo.md
        - wiki/Terminals.md
        - wiki/JIT-Debugging.md
        - wiki/arm64.md
    - 'get-involved.md'
    - 'license.md'
    - 'privacy.md'
    - 'contact.md'
    - 'codeofconduct.md'

